language: python
os: linux
sudo: required
branches:
  only:
  - master
  - stable
services:
- docker
env:
  global:
  - CIBW_BEFORE_BUILD="{pip} install six dask dask-jobqueue --only-binary all"
  - secure: mzeBeHe9b35P5YljfWtYFr+P87Lb53R5mnIaDT//vwpeqogwnd7s7ZwwcxPTChvGvDMJi4m4vKoIzE5IjtLOY4uckuS+n0lfcO+Wkvuv8speylu40NuiBlBxf57A4hYkimvs4LIAJmQkVBBz+9fHLmxn0IfYYQqpCP9YtdoxSce6cUlIf5nQHycLClMo7RvXlHkOKIQEoXbRdFI+EFLsO4VYSHiWZNC3Z3ME3lAtD/k9GwkLpOHVDQnmeX0ahgooKBhd0tSZFKM0HEJKOo9Oj9tgMSXOZ3hbwLzWgexw/HQyHov9T5J4jTVk7C7xg3KGiIaivWMuIAAlxDGR61ux8YtFt5QkQaU4TKk4V4bA/Z1bv+n54K2WBk4owi7ugbOI/0tNy4FwFM9XhAfNsriuDs/V91XTSSEkTFs5C4bNhlmrj8Fp+haFmKyOwnTDDthsgngrQab0QNr7To6bQFSqfZJY5tsPZmUG0StcJUciF+uU/P0e79VoeloGMwwmRtxYhK159YU8VUkpONfp/ZcQ2OQcQmSaPwn+MKWXCLgv4qM0RXWDNkbWJTtvDnO65Rjo4Ytq4mU7dKkR/jQSMWqtP2ATfCj59y+KMRi/MU/db8TaEEFe8AcaGVBpt6T4GPFTinG8FravQh8LZOjWdwpPEDLWtG+VZhLJjJM5s8Fg6X0=
matrix:
  include:
  - python: '3.7'
    dist: xenial
    sudo: true
    if: type != pull_request
    env: CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
  - python: '3.6'
    if: branch = stable OR type = pull_request
    env: CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
  - python: '3.5'
    if: branch = stable
    env: CIBW_SKIP='cp[!3]?-* cp3[!5]-*'
  - python: '2.7'
    if: type != pull_request
    env: CIBW_SKIP='cp[!2]?-* cp2[!7]-*'
install:
- pip install six
- pip install dask dask-jobqueue --only-binary all
- pip install pycodestyle
- echo "$TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION $PYTHON"
- |
  if [[ "$TRAVIS_BRANCH" == "stable" ]] ; then
      pip install cibuildwheel==0.9.4 twine
  else
      if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]] ; then
          pip install coverage coveralls
      fi
  fi
script:
- echo "Running code style checks"
- make styleCheck
- echo "Running build for $TRAVIS_PYTHON_VERSION"
- |
  make compile
  if [[ "$TRAVIS_BRANCH" == "stable" ]] ; then
      # all version targets: build a wheel!
      echo "Generating wheel... (skipping $(CIBW_SKIP))"
      cibuildwheel --output-dir wheelhouse
      ls -l wheelhouse/*
  elif [[ "$TRAVIS_BRANCH" == "master" ]] ; then
      # master branch: regular tests and code coverage analysis
      if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]] ; then
          echo "Running coverage analysis..."
          echo "import chefkoch" > test.py
          coverage run --source=chefkoch test.py
      else
          echo "No test code deployed yet."
      fi
  fi
after_success:
- "./.travis.yml.after_success"
deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel
  tags: true
  on:
    branch: stable
  user:
    secure: F+1Z9O1bcitY86qbwog8bj8wYOq/Ylp7xUa6zYd/ilmPl/iKiESZXbqI5Svs1XbOYN62CCz7NrBXxPhe6FFxD7+J6MWFlwLRv09v7HLotMUqQJKITtyPvHjiX/m8oTkD5qIdqtZDrN+DqVkC7nDDGBVIBvajjuoEY800lGNX9jw6QIXPU6x6JTyI8GiOORwYbD5X2Y8xc/FsXviGSUU9FxmstMp/u5sWG5eOptQnm75a9vWAhFAyjSWQRX/shhin8z7RdOzo9spfUyvitpBYGKaq1mpo768dbDDGdIVygZWGt56Nf3KYkJhR30uenB72WcJV6WSRYj2lRH/fvofD+onNd8T4mm2UviaxEPj7RNuFs1Nbn3bibpHGJtuT+U4QWida2DXh+8fISRVgfQZiC0fUfsY8GwQUfYybPvEjufwoa8rz+AMsprVtsjrdD628Bd9Ccl3a41kG/OIv3uBHxq3FL9mtj7pvIRa18ORyAPo5i/gNgLYoYfyA6UkgC9yRsLA7LNfgSET1Ip5zhnnmS4p9+h4ohUbQgQO29bcZdpuV2ZuJbbuuCyq9UUraq1938GqVH0J4d3d8UKQbMvQgfwUbZeXnYkQZSuWECDddDT/dWfAJw8MeJHKzlQDD/4cXMcL5WdBnaBohPGmw60HPCBpimiGxCRrbqcXiwDYWnm0=
  password:
    secure: jIayMSXoMj61JItOoes6rhlZjA7w5Yi8a/Z2d55Pm9lvFT/iacyaJgA/3RqQhOFynQ+Krf5NFnEek5d+rUxDOYquoDD0Vh6A8fxHzsX1ccfDU7xxu5pK2qxEzGN1xlAi2oC1eoeT6Zk/ZtXxVQ7twtRAuNnXjcpb4dsXnz8979oqtRyRdwughSKhbaBJ0brqsIkQfn/yRHXAO8SYlGJECML2yDKoxhftEKjAStcClp0pKGG+sOlmCZtXUk7TZXw05hHKtS2pgDz1IKQ1wUWsAiR3AqoKkm8HZc+Vj8LG2BySIT9+3Nt9mk9aO4g8L12pJ+p+T+ftWJrtUE8KIu+hLg8yqyciCinsVR+SrYAf6HN9OeeGqMSaUumJhu45Qx+Yf6SaZzl02FObMTHSk1b8/aBGKFDXbUfZCpM+idNwuH+dkRKZSCUEY12xHHEd5E8U8ynLdZr5VMeIrpaRwlGOdyRPVDZnBfrcSFOJmRNi4aAc5gNGlUBkeQzIZubTKqdCJM+GN8CiWe79Wkz6IShptaBsp9Gxe/6lqTCZwtsYsw0708v7RLyVF40lO/C5VyHn/mOBgi5+ctdC+yP+l1E5AWwh/QFmbTposvi+nKC8BLOiFz5NYrKruD0GG3x/JkQEP7R3Vl5S7DQcwW1BEOiw++z1PTrJkosnV91D9qJ0WQI=
