language: python
os: linux
sudo: required
branches:
  only:
  - master
  - stable
services:
- docker
env:
  global:
  - CIBW_BEFORE_BUILD="{pip} install six dask dask-jobqueue --only-binary all"
  - secure: mzeBeHe9b35P5YljfWtYFr+P87Lb53R5mnIaDT//vwpeqogwnd7s7ZwwcxPTChvGvDMJi4m4vKoIzE5IjtLOY4uckuS+n0lfcO+Wkvuv8speylu40NuiBlBxf57A4hYkimvs4LIAJmQkVBBz+9fHLmxn0IfYYQqpCP9YtdoxSce6cUlIf5nQHycLClMo7RvXlHkOKIQEoXbRdFI+EFLsO4VYSHiWZNC3Z3ME3lAtD/k9GwkLpOHVDQnmeX0ahgooKBhd0tSZFKM0HEJKOo9Oj9tgMSXOZ3hbwLzWgexw/HQyHov9T5J4jTVk7C7xg3KGiIaivWMuIAAlxDGR61ux8YtFt5QkQaU4TKk4V4bA/Z1bv+n54K2WBk4owi7ugbOI/0tNy4FwFM9XhAfNsriuDs/V91XTSSEkTFs5C4bNhlmrj8Fp+haFmKyOwnTDDthsgngrQab0QNr7To6bQFSqfZJY5tsPZmUG0StcJUciF+uU/P0e79VoeloGMwwmRtxYhK159YU8VUkpONfp/ZcQ2OQcQmSaPwn+MKWXCLgv4qM0RXWDNkbWJTtvDnO65Rjo4Ytq4mU7dKkR/jQSMWqtP2ATfCj59y+KMRi/MU/db8TaEEFe8AcaGVBpt6T4GPFTinG8FravQh8LZOjWdwpPEDLWtG+VZhLJjJM5s8Fg6X0=
matrix:
  include:
  - python: '3.7'
    dist: xenial
    sudo: true
    if: type != pull_request
    env: CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
  - python: '3.6'
    if: type = pull_request
    env: CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
  - python: '2.7'
    if: branch = master AND type != pull_request
    env: CIBW_SKIP='cp[!2]?-* cp2[!7]-*'
install:
- pip install six
- pip install dask dask-jobqueue --only-binary all
- pip install pycodestyle
- echo "$TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION $PYTHON"
- |
  if [[ "$TRAVIS_BRANCH" == "stable" ]] ; then
      pip install cibuildwheel==0.9.4 twine
  else
      if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]] ; then
          pip install coverage coveralls
      fi
  fi
script:
- echo "Running code style checks"
- make styleCheck
- echo "Running build for $TRAVIS_PYTHON_VERSION"
- |
  make compile
  if [[ "$TRAVIS_BRANCH" == "stable" ]] ; then
      # all version targets: build a wheel!
      echo "Generating wheel... (skipping $(CIBW_SKIP))"
      cibuildwheel --output-dir wheelhouse
      ls -l wheelhouse/*
  elif [[ "$TRAVIS_BRANCH" == "master" ]] ; then
      # master branch: regular tests and code coverage analysis
      if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]] ; then
          echo "Running coverage analysis..."
          echo "import chefkoch" > test.py
          coverage run --source=chefkoch test.py
      else
          echo "No test code deployed yet."
      fi
  fi
after_success:
- "./.travis.yml.after_success"
deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel
  tags: true
  on:
    branch: stable
    python: 3.7
  user:
    secure: F+1Z9O1bcitY86qbwog8bj8wYOq/Ylp7xUa6zYd/ilmPl/iKiESZXbqI5Svs1XbOYN62CCz7NrBXxPhe6FFxD7+J6MWFlwLRv09v7HLotMUqQJKITtyPvHjiX/m8oTkD5qIdqtZDrN+DqVkC7nDDGBVIBvajjuoEY800lGNX9jw6QIXPU6x6JTyI8GiOORwYbD5X2Y8xc/FsXviGSUU9FxmstMp/u5sWG5eOptQnm75a9vWAhFAyjSWQRX/shhin8z7RdOzo9spfUyvitpBYGKaq1mpo768dbDDGdIVygZWGt56Nf3KYkJhR30uenB72WcJV6WSRYj2lRH/fvofD+onNd8T4mm2UviaxEPj7RNuFs1Nbn3bibpHGJtuT+U4QWida2DXh+8fISRVgfQZiC0fUfsY8GwQUfYybPvEjufwoa8rz+AMsprVtsjrdD628Bd9Ccl3a41kG/OIv3uBHxq3FL9mtj7pvIRa18ORyAPo5i/gNgLYoYfyA6UkgC9yRsLA7LNfgSET1Ip5zhnnmS4p9+h4ohUbQgQO29bcZdpuV2ZuJbbuuCyq9UUraq1938GqVH0J4d3d8UKQbMvQgfwUbZeXnYkQZSuWECDddDT/dWfAJw8MeJHKzlQDD/4cXMcL5WdBnaBohPGmw60HPCBpimiGxCRrbqcXiwDYWnm0=
  password:
    secure: CPrGmWHnDuECSbfkdkgQVdqK+IoeZrXDx4P8ZHUtryMeV7LlW91g72WM14xCOwayDRqUWy/NByc9BsSo++vrFAbg1KSnssogu4PNvLiR4R83NVssEZ/UECRtM5EeuamB30xj3KQ30UhTRqvwVF4ha/QAK3dFCFApzi7EQrBh25WnYZZPy+PR6XghqO6JbpaN8JzRr8O3jd+ehZr+q0ORjhG4jAxN/1Se1Lm9jbf9KoozYcAWSrK5rsUzqsYC4C89FZET6WRkbL/dSXToRBQkuw8+5mw00KbJL0OFhddPqe9DkSWAqwjNyAgSq+8HUFY5TM3tRTrsiEanOESHKuXWxJud/HfRKjxgdvZC8gYX+DWzAZ5DeBpPgj6IuF5aADW0rH6/N2bwgkBpFqH5TYbR0ZvmStM5pQpQJmlEppgpibI248K19mUFe4csehvcxmVZBoPOliGC5bVrfGTPIRKwdcjWeN9dQcPpR5g/ETMt9ynKdrOSUx2A0jMV8h9bhALH6XDZWzMoDC1ee4sx+RAw2jQ9va92hh/bvJeoPw18AqpnU0V53zESNq3pX+lYsayoV3OHqx0puZCww5wGC6x9w2SRRn3EJr8wdRpN3TQc2/d+fsC8+NoKo/jocQ7f0p7n+vbuAJO8CRdaBR9Qp6FKNP+B5TxlV/BDY2KzTly3ohQ=
