language: python

install:
- pip install -r requirements-dev.txt

jobs:
  allow_failures:
  - python: "nightly"
  - os: osx
  fast_finish: true

os:
  - linux

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

deploy:
  provider: pypi
  on:
    branch: master
    tags: true

script:
  - make test
  - chef test

after_success:
  - codecov
