compute_a:
    type: python
    resource: steps/dosomething.py
    inputs:
        num_k: num_K
  #      another: num_N
    
    outputs:
        result: z_result

doItTwice_z:
    type: python
    resource: steps/step2.py
    inputs:
        z: z_result

    outputs:
        result: seconds

anotherStep:
    type: python
    resource: steps/LogToLin.py
    inputs:
        beampatternLog: seconds

    outputs:
        result: beampatternLin
