compute_a:
    type: python
    resource: steps/dosomething.py
    inputs:
        data: raw_data
        some_parameter: y
    
    outputs:
        result: z

render_figure_z:
    type: python
    resource: steps/render_figure.py
    inputs:
        data: z
    
    outputs:
        result: figure_z

compile_latex:
    inputs:
        1: tex_paper
    
    outputs:
        1: paper

    type: shell
    resource: steps/compile_latex.sh
    inputs: 