correlation: 
  resource: foo.py
  inputs: 
    inputA: data
    inputB: subsample
    inputC: average
  
  outputs: 
    resultA: radargram
    resultB: num_blocks
    returnFile: plot_radargram
  # space for expansion
  
collect-phase-diagram:
  resource: chef-collect
  inputs: 
    input: radargram,
  outputs: 
    output: radargram-joined
  
plot-phase-diagram: 
  resource: plot-phase-diagram.py
  inputs:
    input: radargram-joined
  
  outputs: 
    ''
